# Generated by Django 5.2.6 on 2026-03-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorize', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512, verbose_name='File Path')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_type', models.CharField(blank=True, max_length=20, verbose_name='File Type')),
                ('file_size', models.IntegerField(default=0, verbose_name='File Size')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Audio File',
                'db_table': 'tb_audiofile',
                'ordering': ['file_name'],
            },
        ),
        migrations.CreateModel(
            name='AudioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_direction', models.CharField(blank=True, max_length=20, verbose_name='Call Direction')),
                ('extension', models.CharField(blank=True, max_length=20, verbose_name='Extension')),
                ('customer_number', models.CharField(blank=True, max_length=20, verbose_name='Customer Number')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Start DateTime')),
                ('end_datetime', models.DateTimeField(auto_now=True, verbose_name='End DateTime')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('custom_field_1', models.CharField(blank=True, max_length=255, verbose_name='Custom Field 1')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorize.agent', verbose_name='Agent')),
                ('audiofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.audiofile', verbose_name='Audio File')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customerinfo', verbose_name='Customer')),
                ('main_db', models.ForeignKey(db_column='maindatabase_id', on_delete=django.db.models.deletion.CASCADE, to='authorize.maindatabase', verbose_name='Main Database')),
            ],
            options={
                'verbose_name': 'Audio Info',
                'db_table': 'tb_audioinfo',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['agent_id', 'start_datetime'], name='tb_audioinf_agent_i_c06649_idx')],
            },
        ),
    ]
