# Generated by Django 4.2.29 on 2026-06-12 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0001_initial'),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioinfo',
            name='delete_option',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Delete Option'),
        ),
        migrations.AddField(
            model_name='audioinfo',
            name='retention_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retention Date'),
        ),
        migrations.AddField(
            model_name='audioinfo',
            name='retention_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retention.retentiontask', verbose_name='Retention Task'),
        ),
        migrations.AddField(
            model_name='audioinfo',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
