# Generated by Django 4.2.29 on 2026-07-15 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audioinfo_delete_option_audioinfo_retention_date_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='CallDirection',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('direction_name', models.CharField(max_length=50, unique=True, verbose_name='Direction Name')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                        ('status', models.BooleanField(default=True, verbose_name='Status')),
                    ],
                    options={
                        'verbose_name': 'Call Direction',
                        'db_table': 'tb_call_direction',
                    },
                ),
                migrations.AlterField(
                    model_name='audiofile',
                    name='duration',
                    field=models.IntegerField(blank=True, help_text='ความยาวหน่วยเป็นวินาที', null=True, verbose_name='Duration'),
                ),
                migrations.AlterField(
                    model_name='audioinfo',
                    name='call_direction',
                    field=models.ForeignKey(blank=True, db_column='call_direction_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.calldirection', verbose_name='Call Direction'),
                ),
            ]
        )
    ]

