# Generated by Django 4.2.29 on 2026-07-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_calldirection_alter_audiofile_duration_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='audioinfo',
                    name='customer',
                ),
            ]
        )
    ]
