"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# โหลด .env จาก root project
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# --- postgres env resolution (use env only; no hardcoded default password) ---
# NOTE: Use POSTGRES_PASSWORD_DEV when DEBUG and set; otherwise use POSTGRES_PASSWORD.
# This computes variables used by DATABASES below and fails fast if password is missing.
POSTGRES_DB = os.environ.get('POSTGRES_DB', 'app_playback')
POSTGRES_USER = os.environ.get('POSTGRES_USER', 'postgres')
POSTGRES_PASSWORD = os.environ.get('POSTGRES_PASSWORD')
POSTGRES_HOST = os.environ.get('POSTGRES_HOST')
POSTGRES_PORT = os.environ.get('POSTGRES_PORT')

if not POSTGRES_PASSWORD:
    raise ImproperlyConfigured('POSTGRES_PASSWORD')

ALLOWED_HOSTS = ['*', '127.0.0.1', '172.27.96.1']
# CORS Configuration
# อนุญาตให้ Frontend (เช่น localhost:6001) ยิง API เข้ามาได้
CORS_ALLOWED_ORIGINS = [
    "https://localhost:6001",
    "https://127.0.0.1:6001",
    "https://localhost:3000",
    "https://172.27.96.1:6001",
    "https://192.168.1.90:6001",
    "https://localhost",
    "https://192.168.1.90",
    "https://192.168.1.202:6001",
    "https://192.168.1.202",
    "https://ecmnichetelcomm.ddns.net",
    "https://ecmnichetelcomm.ddns.net:6001",
    "http://localhost:8080",
    "http://192.168.1.90:8080"
]
SESSION_COOKIE_DOMAIN = None  # ให้ Django ใช้ host จาก request
# Security cookie settings - defaults tuned for development; override via env in production
# In production set SESSION_COOKIE_SECURE and CSRF_COOKIE_SECURE to True (HTTPS required)
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False' if DEBUG else 'True').lower() in ('1', 'true', 'yes')
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False' if DEBUG else 'True').lower() in ('1', 'true', 'yes')
# 'Lax' is a reasonable default; use 'Strict' if you want stricter cross-site blocking
CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Lax')
SESSION_EXPIRE_AT_BROWSER_CLOSE = os.environ.get('SESSION_EXPIRE_AT_BROWSER_CLOSE', 'False').lower() in ('1', 'true', 'yes')

# Cookie name configuration (can be overridden via env)
REFRESH_COOKIE_NAME = os.environ.get('REFRESH_COOKIE_NAME', 'refresh')
SESSION_COOKIE_NAME = os.environ.get('SESSION_COOKIE_NAME', 'sessionid')


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    
    # core sub-apps (models split into packages)
    'apps.core',
    'apps.core.model.customer.apps.CustomerConfig',
    'apps.core.model.audio.apps.AudioConfig',
    'apps.core.model.authorize.apps.AuthorizeConfig',
    'apps.core.model.licenses.apps.LicensesConfig',
    'apps.home',
    'apps.configuration',
    'apps.user_management',
    'apps.log_user',
    'apps.setting',
    'apps.ticket_history',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'apps.core.utils.middleware.DynamicDBHostMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'apps.core.utils.license_middleware.LicenseEnforcementMiddleware',
]

# REST framework + SimpleJWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}

SIMPLE_JWT = {
    # Fallback lifetime values; actual expiry is overridden by DailyExpiry*Token
    # classes which always expire tokens at 23:00 Bangkok time.
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=24),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Custom serializers that enforce the daily 23:00 expiry rule
    'TOKEN_OBTAIN_SERIALIZER': 'apps.core.utils.token_serializers.DailyTokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'apps.core.utils.token_serializers.DailyTokenRefreshSerializer',
}

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Channels layer configuration - prefer Redis if REDIS_URL env is set, otherwise use in-memory layer for dev
if os.environ.get('REDIS_URL'):
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [os.environ.get('REDIS_URL')]
            }
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES_DB,
        'USER': POSTGRES_USER,
        'PASSWORD': POSTGRES_PASSWORD,
        'HOST': POSTGRES_HOST,
        'PORT': POSTGRES_PORT,
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded audio files)
# Serve during development from /media/ and store files under <BASE_DIR>/media
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Network share (SMB) settings used for server-side proxying of audio files
# Configure these in backend/.env
NT_SHARE_HOST = os.environ.get('NT_SHARE_HOST')
NT_SHARE_SHARE = os.environ.get('NT_SHARE_SHARE')
NT_SHARE_USER = os.environ.get('NT_SHARE_USER')
NT_SHARE_PASS = os.environ.get('NT_SHARE_PASS')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email (SMTP) settings - configure via environment variables
# Example for Outlook/Office365 SMTP
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND')
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')

# Config key Nice player
NT_KEY_USERNAME = os.environ.get('NT_KEY_USERNAME')
NT_KEY_PASSWORD = os.environ.get('NT_KEY_PASSWORD')
NT_SECRET_KEY = os.environ.get('NT_SECRET_KEY')

# ถ้าต้องการส่ง Cookie/Token ข้าม Domain
CORS_ALLOW_CREDENTIALS = True

# เพิ่ม CSRF trusted origins เพื่อให้การส่ง cookie/csrf ทำงานจากทั้ง localhost และ LAN
CSRF_TRUSTED_ORIGINS = [
    "https://localhost:6001",
    "https://127.0.0.1:6001",
    "https://192.168.1.90:6001",
    # support nginx default port (no :6001)
    "https://localhost",
    "https://192.168.1.90",
    # frontend LAN host
    "https://192.168.1.202:6001",
    "https://192.168.1.202",
    "https://ecmnichetelcomm.ddns.net",
    "https://ecmnichetelcomm.ddns.net:6001",
]

# License settings — files in ./backend/license/ (mounted read-only in Docker)
LICENSE_DIR = BASE_DIR / 'license'
LICENSE_FILE_PATH = LICENSE_DIR / 'license.json'
LICENSE_PUBLIC_KEY_PATH = LICENSE_DIR / 'public_key.pem'
# HOST_FINGERPRINT is injected at runtime via HOST_FINGERPRINT env var — not a file
# URL of the attestation agent running on the Windows host
LICENSE_AGENT_URL = os.environ.get('LICENSE_AGENT_URL', 'http://host.docker.internal:7890')
