-- INSERT INTO tb_user_permission_detail 
-- ALTER SEQUENCE tb_user_permission_detail_id_seq RESTART WITH 1;

INSERT INTO tb_user_permission_detail ( "user_permission_id", "action", "status", "default", "type") VALUES
-- user_permission_id = 1 
(1,'Audio Records','t','t','access'),
(1,'User Management','t','t','access'),
(1,'Delegate Management','t','t','access'),
(1,'Ticket Management','t','t','access'),
(1,'Role & Permissions','t','t','access'),
(1,'Group & Team','t','t','access'),
-- (1,'Auto Save As File','f','f','access'),
(1,'Audit Log','t','t','access'),
(1,'System Log','t','t','access'),
(1,'Ticket History','t','t','access'),
(1,'Settings','t','t','access'),

(1,'Query Audio Records','t','t','Audio Records'),
(1,'Playback Audio Records','t','t','Audio Records'),
(1,'Download Voice File','t','t','Audio Records'),
(1,'Save As Index','t','t','Audio Records'),
(1,'Delegate Files','t','t','Audio Records'),
-- (1,'Tags / Notes','f','f','Audio Records'),

(1,'Add User','t','t','Management'),
(1,'Edit User','t','t','Management'),
(1,'Delete User','t','t','Management'),
(1,'Change User Status','t','t','Management'),
(1,'Reset User Password','t','t','Management'),
(1,'Save As User Index','t','t','Management'),
(1,'Create Delegate File','t','t','Management'),
(1,'Download Delegate File','t','t','Management'),
(1,'Change Delegate File Status','t','t','Management'),
(1,'Save As Delegate File Index','t','t','Management'),
(1,'Create Ticket','t','t','Management'),
(1,'Download Ticket File','t','t','Management'),
(1,'Change Ticket Status','t','t','Management'),
(1,'Save As Ticket Index','t','t','Management'),
(1,'Ticket Resent','t','t','Management'),

(1,'Edit Base Roles','t','t','Role & Permissions'),
(1,'Add New Custom Roles','t','t','Role & Permissions'),
(1,'Edit Custom Roles','t','t','Role & Permissions'),
(1,'Delete Custom Roles','t','t','Role & Permissions'),

(1,'Add New Group','t','t','Group & Team'),
(1,'Edit Group','t','t','Group & Team'),
(1,'Delete Group','t','t','Group & Team'),
(1,'Add New Team','t','t','Group & Team'),
(1,'Edit Team','t','t','Group & Team'),
(1,'Delete Team','t','t','Group & Team'),

(1,'Save As Audit Log','t','t','Logs'),
(1,'Save As System Log','t','t','Logs'),
(1,'Save As Ticket History','t','t','Logs'),

(1,'Set Column','t','t','Setting'),
(1,'Download Player','t','t','Setting'),

-- user_permission_id = 2 
(2,'Audio Records','t','t','access'),
(2,'User Management','f','f','access'),
(2,'Delegate Management','f','f','access'),
(2,'Ticket Management','f','f','access'),
(2,'Role & Permissions','f','f','access'),
(2,'Group & Team','f','f','access'),
-- (2,'Auto Save As File','f','f','access'),
(2,'Audit Log','t','t','access'),
(2,'System Log','f','f','access'),
(2,'Ticket History','f','f','access'),
(2,'Settings','f','f','access'),

(2,'Query Audio Records','t','t','Audio Records'),
(2,'Playback Audio Records','t','t','Audio Records'),
(2,'Download Voice File','t','t','Audio Records'),
(2,'Save As Index','t','t','Audio Records'),
(2,'Delegate Files','f','f','Audio Records'),
-- (2,'Tags / Notes','f','f','Audio Records'),

(2,'Add User','f','f','Management'),
(2,'Edit User','f','f','Management'),
(2,'Delete User','f','f','Management'),
(2,'Change User Status','f','f','Management'),
(2,'Reset User Password','f','f','Management'),
(2,'Save As User Index','f','f','Management'),
(2,'Create Delegate File','f','f','Management'),
(2,'Download Delegate File','f','f','Management'),
(2,'Change Delegate File Status','f','f','Management'),
(2,'Save As Delegate File Index','f','f','Management'),
(2,'Create Ticket','f','f','Management'),
(2,'Download Ticket File','f','f','Management'),
(2,'Change Ticket Status','f','f','Management'),
(2,'Save As Ticket Index','f','f','Management'),
(2,'Ticket Resent','f','f','Management'),

(2,'Edit Base Roles','f','f','Role & Permissions'),
(2,'Add New Custom Roles','f','f','Role & Permissions'),
(2,'Edit Custom Roles','f','f','Role & Permissions'),
(2,'Delete Custom Roles','f','f','Role & Permissions'),

(2,'Add New Group','f','f','Group & Team'),
(2,'Edit Group','f','f','Group & Team'),
(2,'Delete Group','f','f','Group & Team'),
(2,'Add New Team','f','f','Group & Team'),
(2,'Edit Team','f','f','Group & Team'),
(2,'Delete Team','f','f','Group & Team'),

(2,'Save As Audit Log','t','t','Logs'),
(2,'Save As System Log','f','f','Logs'),
(2,'Save As Ticket History','f','f','Logs'),

(2,'Set Column','t','t','Setting'),
(2,'Download Player','f','f','Setting'),

-- user_permission_id = 3
(3,'Audio Records','t','t','access'),
(3,'User Management','f','f','access'),
(3,'Delegate Management','f','f','access'),
(3,'Ticket Management','f','f','access'),
(3,'Role & Permissions','f','f','access'),
(3,'Group & Team','f','f','access'),
-- (3,'Auto Save As File','f','f','access'),
(3,'Audit Log','f','f','access'),
(3,'System Log','f','f','access'),
(3,'Ticket History','f','f','access'),
(3,'Settings','f','f','access'),

(3,'Query Audio Records','t','t','Audio Records'),
(3,'Playback Audio Records','t','t','Audio Records'),
(3,'Download Voice File','f','f','Audio Records'),
(3,'Save As Index','f','f','Audio Records'),
(3,'Delegate Files','f','f','Audio Records'),
-- (3,'Tags / Notes','f','f','Audio Records'),

(3,'Add User','f','f','Management'),
(3,'Edit User','f','f','Management'),
(3,'Delete User','f','f','Management'),
(3,'Change User Status','f','f','Management'),
(3,'Reset User Password','f','f','Management'),
(3,'Save As User Index','f','f','Management'),
(3,'Create Delegate File','f','f','Management'),
(3,'Download Delegate File','f','f','Management'),
(3,'Change Delegate File Status','f','f','Management'),
(3,'Save As Delegate File Index','f','f','Management'),
(3,'Create Ticket','f','f','Management'),
(3,'Download Ticket File','f','f','Management'),
(3,'Change Ticket Status','f','f','Management'),
(3,'Save As Ticket Index','f','f','Management'),
(3,'Ticket Resent','f','f','Management'),

(3,'Edit Base Roles','f','f','Role & Permissions'),
(3,'Add New Custom Roles','f','f','Role & Permissions'),
(3,'Edit Custom Roles','f','f','Role & Permissions'),
(3,'Delete Custom Roles','f','f','Role & Permissions'),

(3,'Add New Group','f','f','Group & Team'),
(3,'Edit Group','f','f','Group & Team'),
(3,'Delete Group','f','f','Group & Team'),
(3,'Add New Team','f','f','Group & Team'),
(3,'Edit Team','f','f','Group & Team'),
(3,'Delete Team','f','f','Group & Team'),

(3,'Save As Audit Log','f','f','Logs'),
(3,'Save As System Log','f','f','Logs'),
(3,'Save As Ticket History','f','f','Logs'),

(3,'Set Column','t','t','Setting'),
(3,'Download Player','f','f','Setting'),

-- user_permission_id = 4
(4,'Audio Records','t','t','access'),
(4,'User Management','f','f','access'),
(4,'Delegate Management','f','f','access'),
(4,'Ticket Management','f','f','access'),
(4,'Role & Permissions','f','f','access'),
(4,'Group & Team','f','f','access'),
-- (4,'Auto Save As File','f','f','access'),
(4,'Audit Log','f','f','access'),
(4,'System Log','f','f','access'),
(4,'Ticket History','f','f','access'),
(4,'Settings','f','f','access'),

(4,'Query Audio Records','f','f','Audio Records'),
(4,'Playback Audio Records','t','t','Audio Records'),
(4,'Download Voice File','f','f','Audio Records'),
(4,'Save As Index','f','f','Audio Records'),
(4,'Delegate Files','f','f','Audio Records'),
-- (4,'Tags / Notes','f','f','Audio Records'),

(4,'Add User','f','f','Management'),
(4,'Edit User','f','f','Management'),
(4,'Delete User','f','f','Management'),
(4,'Change User Status','f','f','Management'),
(4,'Reset User Password','f','f','Management'),
(4,'Save As User Index','f','f','Management'),
(4,'Create Delegate File','f','f','Management'),
(4,'Download Delegate File','f','f','Management'),
(4,'Change Delegate File Status','f','f','Management'),
(4,'Save As Delegate File Index','f','f','Management'),
(4,'Create Ticket','f','f','Management'),
(4,'Download Ticket File','f','f','Management'),
(4,'Change Ticket Status','f','f','Management'),
(4,'Save As Ticket Index','f','f','Management'),
(4,'Ticket Resent','f','f','Management'),

(4,'Edit Base Roles','f','f','Role & Permissions'),
(4,'Add New Custom Roles','f','f','Role & Permissions'),
(4,'Edit Custom Roles','f','f','Role & Permissions'),
(4,'Delete Custom Roles','f','f','Role & Permissions'),

(4,'Add New Group','f','f','Group & Team'),
(4,'Edit Group','f','f','Group & Team'),
(4,'Delete Group','f','f','Group & Team'),
(4,'Add New Team','f','f','Group & Team'),
(4,'Edit Team','f','f','Group & Team'),
(4,'Delete Team','f','f','Group & Team'),

(4,'Save As Audit Log','f','f','Logs'),
(4,'Save As System Log','f','f','Logs'),
(4,'Save As Ticket History','f','f','Logs'),

(4,'Set Column','f','f','Setting'),
(4,'Download Player','f','f','Setting'),