วิธีติดตั้ง Nginx บน Windows
1. ดาวน์โหลด Nginx สำหรับ Windows ที่ https://nginx.org/en/download.html
2. แตกไฟล์ไปที่ C:\nginx
3. copy ไฟล์ nginx.conf ของโปรเจคไปที่ C:\nginx\conf\nginx.conf
4. copy ไฟล์ cert.pem และ key.pem ไปที่ C:\nginx\conf\
5. รัน Nginx.exe 
6. ทดสอบ Nginx ว่ามี error ไหม 
    - เปิด Command Prompt : cd C:\nginx\nginx-1.29.6  > nginx -t -c conf/nginx.conf 
7. ทดสอบยิง api ว่าผ่านไหมบน cmd : curl -k -v https://192.168.1.90/api/debug/meta/

วิธีตั้งค่าให้ docker / nginx auto start เ
สำหรับ docker 
1. เปิด cmd run administrator
2. รันคำสั่ง : sc config com.docker.service start=auto 
3. รันคำสั่ง : net start com.docker.service

สำหรับ nginx
1. ติดตั้ง NSSM เพื่อจัดการ Nginx เป็น service จาก https://nssm.cc/download
2. แตกไฟล์ NSSM ไปที่ C:\nssm
3. เปิด cmd run administrator : cd C:\nssm\nssm-2.24\win64
4. รันคำสั่ง : nssm install nginx
5. ในหน้าต่าง NSSM setup ให้ตั้งค่าดังนี้
    - Path: C:\nginx\nginx-1.29.6\nginx.exe
    - Startup directory: C:\nginx\nginx-1.29.6
    - กด Install service
6. เปิด cmd run administrator : net start nginx

# วิธีติดตั้ง firewall 
1. เปิด Windows Defender Firewall with Advanced Security
2. คลิกขวาที่ Inbound Rules > New Rule
3. เลือก Port > Next
4. เลือก TCP > Specific local ports > เลือก All ports > Next
5. เลือก Allow the connection > Next
6. เลือก Domain, Private, Public > Next  
7. กรอกชื่อและคำอธิบาย > Finish

#วิธีตั้งค่า pg_hba 
1. เปิดไฟล์ pg_hba.conf ที่ C:\Program Files\PostgreSQL\<version>\data\pg_hba.conf
2. เพิ่มบรรทัดนี้เข้าไปในไฟล์ : 
    host    all             all             0.0.0.0/0               md5
3. บันทึกไฟล์และรีสตาร์ท PostgreSQL เพื่อให้การเปลี่ยนแปลง

#วิธี รีสตาร์ท PostgreSQL 
1. เปิด cmd run administrator
2. รันคำสั่ง : net stop postgresql-x64-<version>
3. รันคำสั่ง : net start postgresql-x64-<version>