สิ่งที่ต้องทำหลังจากเทสฟังก์ชันครบแล้ว
1. เปิดคอมเมนต์ saveLogsInterval หน้า Home.vue 


มีเพิ่มคอมเม้น และ แก้ docker ให้มี timezone และเอา license ของ docker ออกชั่วคราว

# 'apps.core.utils.license_middleware.LicenseEnforcementMiddleware',
