# Generated by Django 5.2.6 on 2026-03-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Customer Contact',
                'db_table': 'tb_customercontact',
                'ordering': ['phone_number'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('customercontact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customercontact', verbose_name='Customer Contact')),
            ],
            options={
                'verbose_name': 'Customer Info',
                'db_table': 'tb_customerinfo',
                'ordering': ['name'],
            },
        ),
    ]
