# Generated by Django 4.2.29 on 2026-07-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_remove_audioinfo_customer'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='customerinfo',
                    name='customercontact',
                ),
                migrations.DeleteModel(
                    name='CustomerContact',
                ),
                migrations.DeleteModel(
                    name='CustomerInfo',
                ),
            ]
        )
    ]
