# Generated by Django 4.2.29 on 2026-06-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRetentionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_type', models.CharField(default='OLDER_THAN', max_length=20)),
                ('older_than_type', models.CharField(default='RELATIVE', max_length=20)),
                ('retention_period', models.CharField(blank=True, max_length=10, null=True)),
                ('older_than_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_once', models.BooleanField(default=False)),
                ('is_recurrence', models.BooleanField(default=True)),
                ('how_often', models.CharField(default='monthly', max_length=20)),
                ('what_day', models.CharField(blank=True, max_length=20, null=True)),
                ('execution_time', models.TimeField(blank=True, null=True)),
                ('delete_option', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_update', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auto_retention_config',
            },
        ),
        migrations.CreateModel(
            name='RetentionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=20)),
                ('delete_option', models.CharField(max_length=50)),
                ('index_count', models.IntegerField(default=0)),
                ('time_period', models.CharField(blank=True, max_length=100, null=True)),
                ('user_create', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_log_path', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
            ],
            options={
                'db_table': 'retention_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO_EXECUTION', 'Auto Execution')], max_length=20)),
                ('delete_option', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RESTORED', 'Restored')], default='RUNNING', max_length=20)),
                ('index_count', models.IntegerField(default=0)),
                ('time_period', models.CharField(blank=True, max_length=100, null=True)),
                ('user_create', models.CharField(max_length=100)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'retention_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
