# Generated by Django 4.2.29 on 2026-06-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentiontask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
