# Generated by Django 4.2.29 on 2026-06-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0002_retentiontask_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
