# Generated by Django 4.2.29 on 2026-06-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0003_retentionlog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoretentionconfig',
            name='permanent_delete_unit',
            field=models.CharField(default='days', max_length=10),
        ),
        migrations.AddField(
            model_name='autoretentionconfig',
            name='permanent_delete_value',
            field=models.IntegerField(default=30),
        ),
    ]
