# Generated by Django 4.2.29 on 2026-06-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0004_autoretentionconfig_permanent_delete_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentiontask',
            name='update_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
