# Generated by Django 5.2.6 on 2026-03-23 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='Agent Group Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.IntegerField(verbose_name='status')),
            ],
            options={
                'verbose_name': 'Agent Group',
                'db_table': 'tb_agent_group',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=255, verbose_name='name_th')),
                ('name_en', models.CharField(max_length=255, verbose_name='name_en')),
            ],
            options={
                'verbose_name': 'department',
                'db_table': 'tb_department',
            },
        ),
        migrations.CreateModel(
            name='MainDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=255, unique=True, verbose_name='Database Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Main Database',
                'db_table': 'tb_maindatabase',
                'ordering': ['database_name'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='User Group Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.IntegerField(verbose_name='status')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Group',
                'db_table': 'tb_user_group',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=50, unique=True, verbose_name='Agent ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('agent_group_id', models.ForeignKey(blank=True, db_column='agent_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorize.agentgroup', verbose_name='AgentGroup')),
            ],
            options={
                'verbose_name': 'Agent',
                'db_table': 'tb_agent',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='SetAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_path', models.CharField(max_length=255, verbose_name='audio_path')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('client_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='client_token')),
                ('selected', models.BooleanField(blank=True, null=True, verbose_name='selected')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'set_audio',
                'db_table': 'tb_set_audio',
                'ordering': ['-selected'],
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.BooleanField(blank=True, null=True)),
                ('maindatabase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorize.maindatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permission', models.ForeignKey(blank=True, db_column='user_permisson_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.userpermission', verbose_name='User Permission')),
            ],
            options={
                'db_table': 'tb_userauth',
            },
        ),
        migrations.CreateModel(
            name='UserFileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('email', models.TextField(verbose_name='email')),
                ('audiofile_id', models.TextField(verbose_name='audiofile_id')),
                ('limit_access_time', models.IntegerField(null=True, verbose_name='limit_access_time')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('start_at', models.DateTimeField(verbose_name='start_at')),
                ('expire_at', models.DateTimeField(verbose_name='expire_at')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('view', models.BooleanField(default=False, verbose_name='view')),
                ('dowload', models.BooleanField(default=False, verbose_name='dowload')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(blank=True, db_column='create_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_shares', to=settings.AUTH_USER_MODEL, verbose_name='create_by')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='file_shares', to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'User File Share',
                'db_table': 'tb_file_share',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('detail', models.TextField(blank=True, verbose_name='Detail')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('client_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='บราวเซอร์ผู้ใช้')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Log',
                'db_table': 'tb_userlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='User Group Name')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('maindatabase', models.TextField(db_column='maindatabase_id', verbose_name='maindatabase')),
                ('status', models.IntegerField(default=1, verbose_name='status')),
                ('user_group', models.ForeignKey(db_column='user_group_id', on_delete=django.db.models.deletion.CASCADE, to='authorize.usergroup', verbose_name='user_group_id')),
            ],
            options={
                'verbose_name': 'User team',
                'db_table': 'tb_user_team',
                'ordering': ['user_group'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=255, verbose_name='user_code')),
                ('phone', models.CharField(max_length=255, verbose_name='user_code')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('session_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='session_token')),
                ('privilege_history', models.BooleanField(blank=True, null=True, verbose_name='สิทธิดูประวัติผู้ใช้')),
                ('create_by', models.ForeignKey(blank=True, db_column='create_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL, verbose_name='create_by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='authorize.userteam', verbose_name='team')),
            ],
            options={
                'verbose_name': 'userprofile',
                'db_table': 'tb_userprofile',
                'ordering': ['user__username'],
            },
        ),
    ]
