# Generated by Django 5.2.6 on 2026-05-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ad_account',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ad_account'),
        ),
    ]
