# Generated by Django 4.2.29 on 2026-07-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0003_ipblacklist'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Department',
                ),
            ]
        )
    ]
