# Generated by Django 5.2.6 on 2026-03-23 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('key_username', models.CharField(max_length=255, verbose_name='key_username')),
                ('key_password', models.CharField(max_length=255, verbose_name='key_password')),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='secret_key')),
            ],
            options={
                'verbose_name': 'config_key',
                'db_table': 'config_key',
            },
        ),
        migrations.CreateModel(
            name='ViewAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.IntegerField(verbose_name='interaction_id')),
                ('database_name', models.TextField(verbose_name='database_name')),
                ('file_path', models.TextField(verbose_name='file_path')),
                ('duration_seconds', models.IntegerField(verbose_name='duration_seconds')),
                ('call_direction', models.IntegerField(verbose_name='call_direction')),
                ('phone_number', models.IntegerField(verbose_name='phone_number')),
                ('extension', models.TextField(verbose_name='extension')),
                ('legacy_agent_id', models.TextField(verbose_name='legacy_agent_id')),
                ('agent_name', models.TextField(verbose_name='agent_name')),
                ('agent_group', models.TextField(verbose_name='agent_group')),
                ('first_name', models.TextField(verbose_name='first_name')),
                ('last_name', models.TextField(verbose_name='last_name')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'view_audio',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_name', models.CharField(max_length=30, verbose_name='favorite_name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('raw_data', models.JSONField(verbose_name='raw_data')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'favorite',
                'db_table': 'tb_favorite_search',
                'ordering': ['favorite_name'],
            },
        ),
        migrations.CreateModel(
            name='SetColumnAudioRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField(verbose_name='raw_data')),
                ('status', models.IntegerField(default=1, verbose_name='status')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='description')),
                ('use', models.BooleanField(default=False, verbose_name='use')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Set Column Audio Record',
                'db_table': 'tb_set_column_audio_record',
                'ordering': ['name'],
            },
        ),
    ]
