# Generated by Django 4.2.29 on 2026-04-24 09:26

from django.db import migrations, models


def set_smb_credentials(apps, schema_editor):
    FileStorageConfig = apps.get_model('home', 'FileStorageConfig')
    config = FileStorageConfig.objects.filter(is_active=1).first()
    if config:
        config.smb_username = 'Administrator'
        config.smb_password = 'Bl@ze389'   # stored plaintext; API endpoint is protected by INSTALLER_SECRET_KEY
        config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='type')),
                ('protocol', models.CharField(max_length=255, verbose_name='key_username')),
                ('host', models.CharField(max_length=255, verbose_name='key_password')),
                ('share_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='secret_key')),
                ('base_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='base_path')),
                ('is_active', models.IntegerField(blank=True, null=True, verbose_name='is_active')),
                ('smb_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='smb_username')),
                ('smb_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='smb_password')),
            ],
            options={
                'verbose_name': 'File Storage Config',
                'db_table': 'file_storage_config',
            },
        ),
        migrations.RunPython(set_smb_credentials, migrations.RunPython.noop),
    ]
