# Generated by Django 4.2.29 on 2026-06-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0003_ipblacklist'),
        ('home', '0006_encrypt_smb_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorageconfig',
            name='base_path',
        ),
        migrations.RemoveField(
            model_name='filestorageconfig',
            name='host',
        ),
        migrations.RemoveField(
            model_name='filestorageconfig',
            name='share_name',
        ),
        migrations.AddField(
            model_name='filestorageconfig',
            name='main_db',
            field=models.ForeignKey(blank=True, db_column='maindatabase_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='authorize.maindatabase', verbose_name='Main Database'),
        ),
        migrations.AddField(
            model_name='filestorageconfig',
            name='network_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Network Path'),
        ),
    ]
