# Generated by Django 5.2.6 on 2026-03-30 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Start DateTime')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='End DateTime')),
            ],
            options={
                'db_table': 'tb_user_permission',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('default', models.BooleanField(verbose_name='Default')),
                ('user_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.userpermission', verbose_name='User Permission')),
            ],
            options={
                'db_table': 'tb_user_permission_detail',
            },
        ),
    ]
