# Generated by Django 4.2.29 on 2026-05-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Action Name')),
            ],
            options={
                'db_table': 'tb_user_permission_action',
            },
        ),
        migrations.CreateModel(
            name='UserPermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Type Name')),
            ],
            options={
                'db_table': 'tb_user_permission_type',
            },
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={},
        ),
        # Remove old columns
        migrations.RemoveField(
            model_name='userpermissiondetail',
            name='action',
        ),
        migrations.RemoveField(
            model_name='userpermissiondetail',
            name='type',
        ),
        # Add new foreign key columns
        migrations.AddField(
            model_name='userpermissiondetail',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.userpermissionaction', verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='userpermissiondetail',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.userpermissiontype', verbose_name='type'),
        ),
    ]
