# Generated by Django 4.2.29 on 2026-05-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDirectorySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_uri', models.CharField(default='ldap://192.168.1.8', max_length=255, verbose_name='AD Server URI')),
                ('domain', models.CharField(default='nichetel.local', max_length=255, verbose_name='AD Domain')),
                ('base_dn', models.CharField(default='cn=Users,dc=nichetel,dc=local', max_length=255, verbose_name='AD Base DN')),
                ('bind_user', models.CharField(default='administrator', max_length=255, verbose_name='AD Bind User')),
                ('bind_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='AD Bind Password (Encrypted)')),
            ],
            options={
                'verbose_name': 'Active Directory Setting',
                'db_table': 'tb_setting_active_directory',
            },
        ),
        migrations.CreateModel(
            name='MailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=255, verbose_name='Email Backend')),
                ('from_email', models.CharField(default='nichetelcomm@gmail.com', max_length=255, verbose_name='Default From Email')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('host_user', models.CharField(default='nichetelcomm@gmail.com', max_length=255, verbose_name='Email Host User')),
                ('host_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Host Password (Encrypted)')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Email Host')),
                ('port', models.IntegerField(default=587, verbose_name='Email Port')),
            ],
            options={
                'verbose_name': 'Mail Setting',
                'db_table': 'tb_setting_mail',
            },
        ),
        migrations.CreateModel(
            name='NetworkShareSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='192.168.1.90', max_length=255, verbose_name='SMB Share Host')),
                ('share', models.CharField(default='Users', max_length=255, verbose_name='SMB Share Name')),
                ('user', models.CharField(default='Administrator', max_length=255, verbose_name='SMB Share User')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='SMB Share Password (Encrypted)')),
                ('client_name', models.CharField(default='nt_playback', max_length=255, verbose_name='SMB Client Name')),
            ],
            options={
                'verbose_name': 'Network Share Setting',
                'db_table': 'tb_setting_network_share',
            },
        ),
    ]
