# Generated by Django 5.2.6
from django.db import migrations

def migrate_env_to_db(apps, schema_editor):
    from django.conf import settings
    # We retrieve the models using apps.get_model to avoid direct imports
    ActiveDirectorySetting = apps.get_model('setting', 'ActiveDirectorySetting')
    NetworkShareSetting = apps.get_model('setting', 'NetworkShareSetting')
    MailSetting = apps.get_model('setting', 'MailSetting')
    
    # Import encryption helpers
    from apps.core.utils.smb_crypto import encrypt_smb_password, is_encrypted

    # 1. AD Settings
    ad_server_uri = getattr(settings, 'AD_SERVER_URI', '')
    ad_domain = getattr(settings, 'AD_DOMAIN', '')
    ad_base_dn = getattr(settings, 'AD_BASE_DN', '')
    ad_bind_user = getattr(settings, 'AD_BIND_USER', '')
    ad_bind_password = getattr(settings, 'AD_BIND_PASSWORD', '')

    if ad_server_uri or ad_domain or ad_base_dn or ad_bind_user:
        enc_password = encrypt_smb_password(ad_bind_password) if ad_bind_password else None
        ActiveDirectorySetting.objects.get_or_create(
            id=1,
            defaults={
                'server_uri': ad_server_uri,
                'domain': ad_domain,
                'base_dn': ad_base_dn,
                'bind_user': ad_bind_user,
                'bind_password': enc_password
            }
        )

    # 2. Network Share Settings
    nt_share_host = getattr(settings, 'NT_SHARE_HOST', '')
    nt_share_share = getattr(settings, 'NT_SHARE_SHARE', '')
    nt_share_user = getattr(settings, 'NT_SHARE_USER', '')
    nt_share_pass = getattr(settings, 'NT_SHARE_PASS', '')
    nt_smb_client_name = getattr(settings, 'NT_SMB_CLIENT_NAME', 'nt_playback')

    if nt_share_host or nt_share_share or nt_share_user:
        enc_pass = encrypt_smb_password(nt_share_pass) if nt_share_pass else None
        NetworkShareSetting.objects.get_or_create(
            id=1,
            defaults={
                'host': nt_share_host,
                'share': nt_share_share,
                'user': nt_share_user,
                'password': enc_pass,
                'client_name': nt_smb_client_name
            }
        )

    # 3. Mail Settings
    email_backend = getattr(settings, 'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
    # If the default is our DbEmailBackend, we fallback to SMTP backend
    if email_backend == 'apps.setting.email_backend.DbEmailBackend':
        email_backend = 'django.core.mail.backends.smtp.EmailBackend'
    default_from_email = getattr(settings, 'DEFAULT_FROM_EMAIL', '')
    email_use_tls = getattr(settings, 'EMAIL_USE_TLS', True)
    email_host_user = getattr(settings, 'EMAIL_HOST_USER', '')
    email_host_password = getattr(settings, 'EMAIL_HOST_PASSWORD', '')
    email_host = getattr(settings, 'EMAIL_HOST', '')
    email_port = getattr(settings, 'EMAIL_PORT', 587)

    if email_host or email_host_user:
        try:
            port_val = int(email_port)
        except Exception:
            port_val = 587
        enc_mail_pass = encrypt_smb_password(email_host_password) if email_host_password else None
        MailSetting.objects.get_or_create(
            id=1,
            defaults={
                'backend': email_backend,
                'from_email': default_from_email,
                'use_tls': email_use_tls,
                'host_user': email_host_user,
                'host_password': enc_mail_pass,
                'host': email_host,
                'port': port_val
            }
        )

class Migration(migrations.Migration):
    dependencies = [
        ('setting', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(migrate_env_to_db),
    ]
