# Generated by Django 4.2.29 on 2026-06-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_populate_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkShareSetting',
        ),
    ]
